version: "3.7"
services:
  react:
    container_name: "react"
    build: 
      context: ./site/client
      dockerfile: Dockerfile
    env_file: 
      - ./environments/.env.node
    ports:
      - "3000:8080"
    volumes:
      - ./site/client:/usr/src/app
    depends_on:
      - node

  node:
    container_name: "node"
    build: 
      context: ./site/server
      dockerfile: Dockerfile
    env_file: 
      - ./environments/.env.node
    ports:
      - "5000:5000"
    volumes:
      - ./site/server:/usr/src/app
    depends_on:
      - api
  
  api:
    container_name: "api"
    build:
      context: ./apis/scraper
      dockerfile: Dockerfile
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    env_file: 
      - ./environments/.env.api
    ports:
      - "8002:8000"
    depends_on:
      - mongo
    
  mongo:
    container_name: "mongo"
    image: "mongo"
    env_file: 
      - ./environments/.env.mongo
    volumes:
      - mongo:/data/db
    ports:
      - '27017-27019:27017-27019'

volumes:
  mongo: